@startuml Todoist
    class User {
        # id: int
        + login: string
        + password: password
        + name: string
        + surname: string
        + patronymic: string
        + email: string
        + admin: boolean
    }

    class Task {
        # id: int
        + name: string
        + description: string
        + status: string
        + time: time
    }
    
    class Comment {
        # id: int
        + description: string
    }

    class Groups {
        # id: int
        + name: string
    }

    hexagon привязывание {

    }

    hexagon оставление {

    }


    hexagon привязывание_1 {

    }

    hexagon оставление_1 {

    }

    hexagon Role {

    }

    User "о" -down-> привязывание
    привязывание -up-> "m" Task
    User "o" -up-> оставление
    оставление -> "m" Comment
    Comment "m" --> привязывание_1
    привязывание_1 -> "o" Task
    Comment "o" -> оставление_1
    оставление_1 -> "m" Comment
    User "m" ----> Role
    Role --> "m" Groups
@enduml
