@startuml 
    class User {
        + login: string
        + password: password
        + name: string
        + surname: string
        + patronymic: string
        + email: email
        + admin: boolean
    }

    class Task {
        + name: string
        + description: string
        + status: string
    }
    
    class Comment {
        + description: string
    }

    class Project {
        + name: string
        + description: string
    }

    class Permision {
        + right_to_create: string
        + right_to_delete: string
    }

    
    Comment *--> User : Один ко многим
    Comment *--> Task : Один ко многим
    Comment *--> Comment : Один ко многим
    Task *---> Project : Один ко многим
    Task *--> User : Один ко многим
    Permision *---> Project: Один ко многим
    Permision *--> User: Один к одному
@enduml