@startuml Todoist
    class User {
        # id: int
        + login: string
        + password: password
        + name: string
        + surname: string
        + patronymic: string
        + email: string
        + admin: boolean
    }

    class Task {
        # id: int
        + name: string
        + description: string
        + status: string
        + time: time
    }
    
    class Comment {
        # id: int
        + description: string
    }

    class Groups {
        # id: int
        + name: string
    }

    class Role {
        # id: int
        + permission: int
    }

    hexagon привязать {

    }

    hexagon оставить {

    }

    hexagon привязать_1 {

    }

    hexagon оставить_1 {

    }

    User "о" -down-> привязать
    привязать -up-> "m" Task
    User "o" -up-> оставить
    оставить -> "m" Comment
    Comment "m" --> привязать_1
    привязать_1 -> "o" Task
    Comment "o" -> оставить_1
    оставить_1 -> "m" Comment
    User "m" <----> Role
    Role <--> "m" Groups
@enduml
