@startuml diagram
    class User {
        + login: string
        + password: digest
        + name: string
        + surname: string
        + patronymic: string
        + email: string
        + admin: boolean
    }

    class Task {
        # project_id: int
        # user_id: int
        # owner_id: int
        + name: string
        + description: text
        + status: string
    }
    
    class Comment {
        # user_id: int
        # comment_id: int
        # task_id: int
        + description: text
    }

    class Project {
        + name: string
        + description: text
    }

    class Permission {
        # user_id: int
        # project_id: int
        + edit: boolean
        + read: boolean
    }
    
    User "о" o-right-* "м" Comment
    User "o" o-down-* "м  " Task
    User "о" o-down-* "м  " Task
    Task "м" *-o "o " Project
    Project "о" o--* "м  " Permission
    Permission "м" *--o "о" User
    Comment "о" o--* "м" Comment
    Comment "м" *--o "о" Task
@enduml