@startuml Todoist
    class User {
        # id: int
        + login: string
        + password: password
        + name: string
        + surname: string
        + patronymic: string
        + email: string
        + admin: boolean
    }

    class Task {
        # id: int
        + name: string
        + description: string
        + status: string
        + time: time
    }
    
    class Comment {
        # id: int
        + description: string
    }

    class Calendar {
        # id: int
        + name: string
        + description: string
    }

    class Groups {
        # id: int
        + name: string
    }

    class Permission {
        # id: int
        + name: string
        + access: boolean
    }
    
    hexagon открытие {

    }

    hexagon привязывание {

    }

    hexagon оставление {

    }


    hexagon привязывание_1 {

    }

    hexagon взаимодействие {

    }

    hexagon оставление_1 {

    }

    hexagon администрирование {

    }

    hexagon привязывание_2 {

    }

    User "о" -> открытие
    открытие -> "o" Calendar
    Calendar "o" -> привязывание
    привязывание -> "m" Task
    User "o" --> оставление
    оставление -> "m" Comment
    Comment "m" --> привязывание_1
    привязывание_1 -> "o" Task
    User "m" ---> взаимодействие
    взаимодействие -> "o" Groups
    Comment "o" -> оставление_1
    оставление_1 -> "m" Comment
    User "o" ----> администрирование
    администрирование -> "m" Permission
    Permission "m" -> привязывание_2
    привязывание_2 -> "o" Groups
@enduml
